### ISSUE TITLE
How to track the version of the corresponding source material?

### ISSUE THREAD

**Issue by ento** [DiscoverMeteor/DiscoverMeteor_Ja#6]
Discover Meteor is an ongoing work. The original will receive updates and improvements even after we complete the translation. The translation needs to be updated too.

It would be useful, when updating, to be able to view the diff between the latest source and the translated one.

Would it be feasible to make it a rule to record the commit hash of the English source file in the YAML front matter? Something like:

```
source: af85563fad385506e695e1f7c27ace005883d24b
```

**Comment by SachaG** [comment]
There's already the version number but you're right, maybe the commit source would be helpful as well.

But would this be per-file? Or just on the changelog?

**Comment by ento** [comment]
I was thinking of doing this on a per-file basis, but I hadn't realized the book is already versioned. So then, it'd be simpler to:
1. Create a tag for each version on the English repository
2. Agree on a target version of the book to translate and note it somewhere
   - on the changelog, readme and/or GitHub milestones?
3. Always work from the corresponding tag of the source repo

**Comment by SachaG** [comment]
Sounds good, just tagged the last update:

https://github.com/DiscoverMeteor/DiscoverMeteor_En/releases/tag/1.7

When you say "Agree on a target version of the book to translate", I assume this would be per language? If so yeah I think GitHub milestones would work. 

The only problem is what happens if we release version 1.8 while you're working on 1.7? Should people keep working on 1.7, or switch to 1.8 right away?

**Comment by ento** [comment]
Great!
Yes, "target version" would be per language.

> The only problem is what happens if we release version 1.8 while you're working on 1.7?

Hmm, I guess it depends on the changes between the versions.

If it's a major overhaul and we can expect people to want to read the previous version in a coherent state from head to tail, then it makes sense to finish 1.7 first and move on to the next version.

If not, then I'd say it's better to base off from the latest version when starting a new chapter, to save the hassle of diffing and applying the changes. If someone is in the middle of translating a chapter, it'd be up to them to choose when to switch to the latest version.

Considering these cases, we might want to track the versions on a per-file basis after all.

**Comment by SachaG** [comment]
I think the best way is to just try out a method and see what happens. We're kind of letting each translation project organize as they want, so as long as everybody in the repo agrees feel free to establish a new rule :)

**Comment by ento** [comment]
@SachaG Alrighty =)

Superseded by #11
