### ISSUE TITLE
Shinichi-Matsumoto さんが沢山翻訳作業をしています。

### ISSUE THREAD

**Issue by m0a** [DiscoverMeteor/DiscoverMeteor_Ja#7]
日本語で失礼します。
翻訳作業を手伝おうと思いましたら、Shinichi-Matsumotoさんが大量に翻訳されています。
ですが、プッシュされていないみたいです。
もったいないので、本家に取り込んだ方がいいかと思います。

ここに書くべきか悩んだんですが、Shinichi-Matsumotoさんに連絡する手段がないので。(⌒-⌒; )
勝手にやるのって権利的にまずかったりしますでしょうか？

**Comment by gabriel-wilkes** [comment]
Abe-san, if you would like to push Matsumoto-san's translations, please go ahead. That would be very helpful and much appreciated. There are also many areas where he is not sure of the translation and puts question marks, if you can clean up those parts too it would be be even better. Thanks!

**Comment by m0a** [comment]
Thank you for the reply
I began the work
